<?php

namespace App\Http\Controllers\Front;

/**
 * Generated by RTKit.
 */

use App\Models\Address;
use Illuminate\Http\Request;
use App\Http\Requests;

class AddressController extends FrontController
{
    /**
     * Show addresses list of current user.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request, Address $address) {
        $list = $address->fetchByUser($request->user()->id);
        return view('front/address', [
            'list' => $list
        ]);
    }

    public function add() {
        return view('front/address_add');
    }

    public function postAdd(Request $request, Address $address) {
        $request->flash();
        $this->validate($request, [
            'zone_id' => ['required', 'numeric', 'between:110000,820000'],
            'detail' => 'required',
            'receiver' => 'required',
            'contact' => ['required', 'regex:/(1\d{10})|((0\d{2})|(0\d{3}))\d{7}/']
        ],[
            'zone_id.required' => trans('user.zone_id_required'),
            'zone_id.between' => trans('user.zone_id_between'),
            'detail.required' => trans('user.detail_required'),
            'receiver.required' => trans('user.receiver_required'),
            'contact.required' => trans('user.contact_required'),
            'contact.regex' => trans('user.contact_regex')
        ]);
        $address->store($request);

        return redirect(url('/address'));
    }

    public function edit($id) {
        $row = Address::find($id);
        return view('front/address_edit', ['row' => $row]);
    }

    public function postEdit(Request $request, Address $address) {
        $address->updateOne($request);
        return redirect(url('/address'));
    }

    public function remove($id) {
        Address::destroy($id);
        return redirect(url('/address'));
    }
}
