<?php

namespace App\Http\Controllers\Front;

/**
 * Generated by RTKit.
 */

use Illuminate\Http\Request;
use App\Http\Requests;

class AddressController extends FrontController
{

    /**
     * Show addresses list of current user.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request) {

        
        return display();
    }

    public function add() {
        return display();
    }

    public function postAdd(Request $request) {
        return redirect(url(''));
    }

    public function edit($id) {
        return display();
    }

    public function postEdit(Request $request) {
        return redirect(url(''));
    }

    public function remove($id) {
        return redirect(url(''));
    }
}
