<?php

namespace App\Http\Controllers\Console\Settings;

/**
 * Generated by RTKit.
 */

use App\Http\Controllers\Console\ConsoleController;
use App\Http\Controllers\Front\FrontController;
use App\Models\Permission;
use Illuminate\Http\Request;
use App\Http\Requests;

class PermissionController extends ConsoleController {

    public function __construct(){
        parent::__construct();
        $this->tabs = [
            [
                'url' => url('/permissions'),
                'name' => '权限管理'
            ],
            [
                'url' => url('/permissions/add'),
                'name' => '添加权限'
            ],
        ];
    }

    public function index($page = 1) {

        $list = Permission::fetchBlock();
        $permissionsCount = Permission::count();
        $pages = FrontController::pages('/permissions', $permissionsCount, $page);

        return view('console.permissions_list', [
            'tabs' => $this->tabs,
            'list' => $list,
            'active' => 0,
            'pages' => $pages
        ]);
    }

    public function add(Request $request) {
        if ($request->isMethod('post')) {
            $permission = new Permission();
            $permission->store($request);
            return redirect('/permissions');
        }

        return view('console.permissions_add', [
            'tabs' => $this->tabs,
            'active' => 0,
        ]);
    }

    public function edit(Request $request, $id) {
        if ($request->isMethod('post')) {
            $data = [
                'name' => $request->name,
                'display_name' => $request->display_name,
                'description' => $request->description
            ];
            Permission::updateOne($id, $data);
            return redirect('/permissions');
        }

        $row = Permission::find($id);
        return view('console.permissions_edit', [
            'row' => $row,
            'tabs' => $this->tabs,
            'active' => 0,
        ]);
    }

    public function remove($id) {
        Permission::destroy($id);
        return redirect(url('/permissions'));
    }
}
