<?php

namespace App\Http\Controllers\Console\Settings;

/**
 * Generated by RTKit.
 */

use App\Http\Controllers\Console\ConsoleController;
use App\Http\Controllers\Front\FrontController;
use App\Models\Role;
use Illuminate\Http\Request;

class RolesController extends ConsoleController
{
    public function __construct(){
        parent::__construct();
        $this->tabs = [
            [
                'url' => url('/roles'),
                'name' => '角色管理'
            ],
            [
                'url' => url('/roles/add'),
                'name' => '添加角色'
            ],
        ];
    }

    public function index($currentPage = 1) {
        $pagesCount = ceil(Role::count() / 10);
        $pages = FrontController::pages('/roles', $pagesCount, $currentPage);
        $list = Role::fetchBlock($currentPage);

        return view('console.roles_list', [
            'list' => $list,
            'tabs' => $this->tabs,
            'pages' => $pages,
            'active' => 0
        ]);
    }

    public function add(Request $request) {

        if ($request->isMethod('post')) {
            $role = new Role();
            $role->store($request);
            return redirect('/roles');
        }

        return view('console.roles_add', [
            'tabs' => $this->tabs,
            'active' => 1
        ]);
    }

    public function edit(Request $request, $id) {

        if ($request->isMethod('post')) {
            $data = [
                'name' => $request->name,
                'display_name' => $request->display_name,
                'description' => $request->description
            ];
            Role::updateOne($id, $data);
            return redirect('/roles');
        }
        
        $row = Role::find($id);

        return view('console.roles_edit', [
            'tabs' => $this->tabs,
            'active' => 1,
            'row' => $row
        ]);
    }


    public function remove($id) {
        Role::destroy($id);
        return redirect(url('/roles'));
    }
}
