<?php

namespace App\Http\Controllers\Console\Settings;

/**
 * Generated by RTKit.
 */

use App\Http\Controllers\Console\ConsoleController;
use App\Http\Controllers\Front\FrontController;
use App\Models\Permission;
use App\Models\PermissionRole;
use App\Models\Role;
use Illuminate\Http\Request;
use DB;

class RolesController extends ConsoleController
{
    public function __construct(){
        parent::__construct();
        $this->tabs = [
            [
                'url' => url('/roles'),
                'name' => '角色管理'
            ],
            [
                'url' => url('/roles/add'),
                'name' => '添加角色'
            ],
        ];
    }

    public function index($currentPage = 1) {
        $pagesCount = ceil(Role::count() / 10);
        $pages = FrontController::pages('/roles', $pagesCount, $currentPage);
        $list = Role::fetchBlock($currentPage);

        return view('console.roles_list', [
            'list' => $list,
            'tabs' => $this->tabs,
            'pages' => $pages,
            'active' => 0
        ]);
    }

    public function add(Request $request) {

        if ($request->isMethod('post')) {
            $role = new Role();
            $role->store($request);

            $permissions = $request->permissions;
            foreach ($permissions as $k => $v) {
                $permissions[$k] = [
                    'id' => $v
                ];
            }
            $role->attachPermissions($permissions);
            return redirect('/roles');
        }

        $permissions = Permission::get();
        return view('console.roles_add', [
            'tabs' => $this->tabs,
            'active' => 1,
            'permissions' => $permissions
        ]);
    }

    public function edit(Request $request, $id) {

        if ($request->isMethod('post')) {
            $data = [
                'name' => $request->name,
                'display_name' => $request->display_name,
                'description' => $request->description
            ];

            DB::beginTransaction();
            $affectedOne = Role::updateOne($id, $data);


            $role = new Role();
            $role->id = $id;
            $affected = PermissionRole::where('role_id', $id)->delete();
            $permissions = $request->permissions;

            if (count($permissions) > 0) {
                foreach ($permissions as $k => $v) {
                    $permissions[$k] = [
                        'id' => $v
                    ];
                }
                $role->attachPermissions($permissions);
            }

            if ($affectedOne !== false && $affected !== false)
                DB::commit();
            else
                DB::rollBack();
            
            return redirect('/roles');
        }
        
        $row = Role::find($id);
        $permissions = Permission::get();
        foreach ($permissions as $key => $permission) {
            $permissions[$key]->checked = false;
            foreach ($row->permissions as $assigned) {
                if ($permission->id == $assigned->id) {
                    $permissions[$key]->checked = true;
                    break;
                }
            }
        }
        return view('console.roles_edit', [
            'tabs' => $this->tabs,
            'active' => 1,
            'row' => $row,
            'permissions' => $permissions
        ]);
    }


    public function remove($id) {
        Role::destroy($id);
        return redirect(url('/roles'));
    }
}
