<?php

namespace App\Http\Controllers\Test;

/**
 * Generated by RTKit.
 */

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class MusicController extends Controller
{
    public function index() {
        return display();
    }

    public function add() {
        return display();
    }

    public function postAdd(Request $request) {
        return redirect(url(''));
    }

    public function edit($id) {
        return display();
    }

    public function postEdit(Request $request) {
        return redirect(url(''));
    }

    public function remove($id) {
        return redirect(url(''));
    }
}
